// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc0oWfx1iRSUjMp7-PJeKfFxGIesnl1pU',
    appId: '1:95255292842:web:4b25290af31900653a99d3',
    messagingSenderId: '95255292842',
    projectId: 'todo-3eb5d',
    authDomain: 'todo-3eb5d.firebaseapp.com',
    storageBucket: 'todo-3eb5d.appspot.com',
    measurementId: 'G-9ZY2547HKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCljfd0VHPY696jafG2YpkOZnn_uhEuRPk',
    appId: '1:95255292842:android:c9f834db62c617d73a99d3',
    messagingSenderId: '95255292842',
    projectId: 'todo-3eb5d',
    storageBucket: 'todo-3eb5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0FQU-YYXkyAEqxKLbSyz7lB_FjaqxJO0',
    appId: '1:95255292842:ios:c50406f9aa050eef3a99d3',
    messagingSenderId: '95255292842',
    projectId: 'todo-3eb5d',
    storageBucket: 'todo-3eb5d.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0FQU-YYXkyAEqxKLbSyz7lB_FjaqxJO0',
    appId: '1:95255292842:ios:c50406f9aa050eef3a99d3',
    messagingSenderId: '95255292842',
    projectId: 'todo-3eb5d',
    storageBucket: 'todo-3eb5d.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc0oWfx1iRSUjMp7-PJeKfFxGIesnl1pU',
    appId: '1:95255292842:web:2901a7a9b1e86f293a99d3',
    messagingSenderId: '95255292842',
    projectId: 'todo-3eb5d',
    authDomain: 'todo-3eb5d.firebaseapp.com',
    storageBucket: 'todo-3eb5d.appspot.com',
    measurementId: 'G-Z6YJG68DW1',
  );
}
